module.exports = {
	STATUS: {
		PENDING: 'PENDING',
		SUCCEED: 'SUCCEED',
        FAILED: 'FAILED',
	},
	TYPE: {
		TRANSFER: 'TRANSFER',
		TOPUP: 'TOPUP',
		WITHDRAW: 'WITHDRAW',
		WALLETOBANK: 'WALLETOBANK '
	}
};