module.exports = {
	STATUS: {
		PENDING: 'PENDING',
		SUCCEED: 'SUCCEED',
        FAILED: 'FAILED',
		EXPIRED: 'EXPIRED'
	},
	TYPE: {
		TRANSFER: 'TRANSFER',
		TOPUP: 'TOPUP',
		WITHDRAW: 'WITHDRAW',
		WALLETOBANK: 'WALLETOBANK',
		NAPAS: 'NAPAS'
	}
};